# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:46
from __future__ import unicode_literals

import account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, storage=account.utils.OverwriteStorage(), upload_to=account.utils.UploadToPathAndRename(b'profile_avatars'))),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
