# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 02:31
from __future__ import unicode_literals

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=account.utils.OverwriteStorage(), upload_to=account.utils.UploadToPathAndRename(b'profile_avatars')),
        ),
    ]
